// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhxuTnxdvS21XcR_y1e7aFAqKTyKeuYDE',
    appId: '1:659176701520:web:dfbca009962afe655a1b55',
    messagingSenderId: '659176701520',
    projectId: 'chat-app-3ff8d',
    authDomain: 'chat-app-3ff8d.firebaseapp.com',
    storageBucket: 'chat-app-3ff8d.appspot.com',
    measurementId: 'G-FY7CYMFG79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyivA1OtoZ_RmQ9nlEY2g4UZ6XIBGzlgs',
    appId: '1:659176701520:android:9eba2ac5253aadf55a1b55',
    messagingSenderId: '659176701520',
    projectId: 'chat-app-3ff8d',
    storageBucket: 'chat-app-3ff8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe3TTZayKn-wVNSRpm0lQzgYIAvBbmaDE',
    appId: '1:659176701520:ios:e7e2876ecdb1fbc75a1b55',
    messagingSenderId: '659176701520',
    projectId: 'chat-app-3ff8d',
    storageBucket: 'chat-app-3ff8d.appspot.com',
    iosBundleId: 'com.example.chatFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe3TTZayKn-wVNSRpm0lQzgYIAvBbmaDE',
    appId: '1:659176701520:ios:e7e2876ecdb1fbc75a1b55',
    messagingSenderId: '659176701520',
    projectId: 'chat-app-3ff8d',
    storageBucket: 'chat-app-3ff8d.appspot.com',
    iosBundleId: 'com.example.chatFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhxuTnxdvS21XcR_y1e7aFAqKTyKeuYDE',
    appId: '1:659176701520:web:9e6ce4a319de42035a1b55',
    messagingSenderId: '659176701520',
    projectId: 'chat-app-3ff8d',
    authDomain: 'chat-app-3ff8d.firebaseapp.com',
    storageBucket: 'chat-app-3ff8d.appspot.com',
    measurementId: 'G-KF05S0XBMH',
  );

}